### ISSUE TITLE
Normalized environment variable

### ISSUE THREAD

**Issue by scolladon** [scolladon/postman-salesforce-apis#10]
Define naming convention to distinguish settable by user variable and variable set by the system

**Comment by pozil** [comment]
Proposed convention: uppercase text surrounded with `<>`:
```
<REPLACE_ME>
```

**Comment by scolladon** [comment]
I propose the following :
- all variable should be lower camel case: myVariable
- variable set by the user should start by a letter: userSettableVariable
- variable set by the system should start by an underscore: _systemSettableVariable

applied to existing : 
url => url
version => version
username => username
password => password
secret_token => secretToken
clientId => clientId
clientSecret => clientSecret
redirectUrl => redirectUrl
init_access_token => initAccessToken
site => site
key => to remove : seems to not be used
env => to remove : seems to not be used
orgId => _orgId
userId => _userId
endpoint => _endpoint
access_token => _accessToken
refresh_token => _ refreshToken

**Comment by pozil** [comment]
Sounds good, let's try to separate two concepts in docs: variables and placeholders.

Here's what I propose as definitions:
- **Variables** are set in the Postman Environment dialog. This doesn't modify the requests. Syntax: we use the convention that you defined.
- **Placeholders** are request parts that needs to be replaced with a value. This modifies the requests. Syntax: uppercase text with underscores surrounded with `<>`

**Comment by scolladon** [comment]
Wonderfull !
I think we don't need to add placeholder in the template environment, they will be added when we set them in the code.
This way we expose the variable in the environment template and we let the scripts add the system one it requires : 
url => url
version => version
username => username
password => password
secret_token => secretToken
clientId => clientId
clientSecret => clientSecret
redirectUrl => redirectUrl
init_access_token => initAccessToken
site => site
key => to remove : seems to not be used
env => to remove : seems to not be used
orgId => <ORG_ID> removed from template
userId => <USER_ID> removed from template
endpoint => <ENDPOINT> removed from template
access_token => <ACCESS_TOKEN> removed from template
refresh_token => <REFRESH_TOKEN> removed from template
other set variable like jobId and batchId should be removed
