### ISSUE TITLE
Getting Error 

### ISSUE THREAD

**Issue by vikilleaks** [scolladon/postman-salesforce-apis#22]
I followed all the instructions given in the README.md
For REST, all of the GET requests are working but the POST requests aren't working.
For "Get Appointment Slots" and "Get Appointment Candidates" POST requests, I am getting this error:
[{"errorCode":"BAD_REQUEST","message":"Value does not match expected type at [line:2, column:2]"}]
Any ideas to resolve this?
<img width="1784" alt="Screenshot 2020-06-14 at 12 38 57 AM" src="https://user-images.githubusercontent.com/32481163/84577160-77573800-add7-11ea-8ec8-2321aba1ffb4.png">

**Comment by scolladon** [comment]
Hi !

You need to put values in the body of the post to make it works following your needs.
The list of attributes and behaviour are in the documentation https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/requests_ls_getappointmentcandidates.htm

In the request, go to the body tab and change the values in the JSON Body.
Let me know if it is ok for you

Seb

**Comment by vikilleaks** [comment]
Thanks.
